# Generated by Django 5.0.4 on 2024-05-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnis', '0007_alter_user_date_of_birth_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=101, null=True),
        ),
    ]
